/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ar_jni_JNIExample */

#ifndef _Included_com_ar_jni_JNIExample
#define _Included_com_ar_jni_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ar_jni_JNIExample
 * Method:    echo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ar_jni_JNIExample_echo__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ar_jni_JNIExample
 * Method:    echo
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ar_jni_JNIExample_echo__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_ar_jni_JNIExample
 * Method:    echo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ar_jni_JNIExample_echo__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ar_jni_JNIExample
 * Method:    sum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_ar_jni_JNIExample_sum
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
